- name: Refresh APT cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages (dist-upgrade)
  ansible.builtin.apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes

- name: Install essential OS packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - wget
      - git
      - unzip
      - lsb-release
      - software-properties-common
    state: present

- name: Ensure Python3 and pip3 are installed
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present

- name: Set system timezone to UTC
  community.general.timezone:
    name: Etc/UTC
